-
  name: 'head styles'
  uriPattern: 'DynamicResources/Head/styles.min.css'
  defaults:
    '@package': 'NeosRulez.DynamicResources'
    '@controller': 'Resource'
    '@format': 'css'
    '@action': 'headStyles'
-
  name: 'head scripts'
  uriPattern: 'DynamicResources/Head/scripts.min.js'
  defaults:
    '@package': 'NeosRulez.DynamicResources'
    '@controller': 'Resource'
    '@format': 'js'
    '@action': 'headScripts'
-
  name: 'footer styles'
  uriPattern: 'DynamicResources/Footer/styles.min.css'
  defaults:
    '@package': 'NeosRulez.DynamicResources'
    '@controller': 'Resource'
    '@format': 'css'
    '@action': 'footerStyles'
-
  name: 'head scripts'
  uriPattern: 'DynamicResources/Footer/scripts.min.js'
  defaults:
    '@package': 'NeosRulez.DynamicResources'
    '@controller': 'Resource'
    '@format': 'js'
    '@action': 'footerScripts'
