Neos:
  Flow:
    mvc:
      routes:
        'NeosRulez.DynamicResources': true
  Neos:
    fusion:
      autoInclude:
        NeosRulez.DynamicResources: true
NeosRulez:
  DynamicResources:
    resources:
      head:
        scripts:
          testJs: 'resource://NeosRulez.DynamicResources/Private/JavaScript/test.js'
          testJs2: 'resource://NeosRulez.DynamicResources/Private/JavaScript/test2.js'
        styles:
          testCss: 'resource://NeosRulez.DynamicResources/Private/Styles/test.scss'
          testCss2: 'resource://NeosRulez.DynamicResources/Private/Styles/test2.scss'
      footer:
        scripts:
          testJs: 'resource://NeosRulez.DynamicResources/Private/JavaScript/test.js'
          testJs2: 'resource://NeosRulez.DynamicResources/Private/JavaScript/test2.js'
        styles:
          testJs: 'resource://NeosRulez.DynamicResources/Private/Styles/test.scss'
          testJs2: 'resource://NeosRulez.DynamicResources/Private/Styles/test2.scss'